version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAMES}

  django-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: djangoapp
    restart: always
    ports:
      - 8085:8000
    environment:
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_USER=${DB_USER}
      - DATABASE_NAME=${DB_NAMES}
      - DATABASE_PORT=5432
    depends_on: 
      - postgres
    
volumes:
  database-data: